### ISSUE TITLE
number of client

### ISSUE THREAD

**Issue by DongYan1121** [wenzhu23333/Federated-Learning#5]
Hello, I would like to ask if the number of training users can be added to this

**Comment by wenzhu23333** [comment]
For MNIST, Cifar-10, Fashion-MNIST, you can change in the utils/options.py.
For FEMNIST, Shakespeare, changing the number of training users is useless, because these datasets are sampled from project leaf, you can sample by yourself. Or you can rewrite code in utils/dataset.py by yourself to fulfill this requirement.
